import { DistDto } from 'src/types/dist.dto';

export class DefaultData {
  static dist: DistDto[] = [
    {
      id: 1,
      type: 'expenseType',
      distKey: '饮食',
      distValue: '饮食',
      sort: 1,
    },
    {
      id: 2,
      type: 'expenseType',
      distKey: '娱乐',
      distValue: '娱乐',
      sort: 2,
    },
    {
      id: 3,
      type: 'expenseType',
      distKey: '生活',
      distValue: '生活',
      sort: 3,
    },
    {
      id: 4,
      type: 'expenseType',
      distKey: '医疗',
      distValue: '医疗',
      sort: 4,
    },
    {
      id: 5,
      type: 'expenseType',
      distKey: '学习',
      distValue: '学习',
      sort: 5,
    },
    {
      id: 6,
      type: 'expenseType',
      distKey: '社交',
      distValue: '社交',
      sort: 6,
    },
    {
      id: 7,
      type: 'expenseType',
      distKey: '通讯',
      distValue: '通讯',
      sort: 7,
    },
    {
      id: 8,
      type: 'expenseType',
      distKey: '交通',
      distValue: '交通',
      sort: 8,
    },
    {
      id: 9,
      type: 'expenseType',
      distKey: '住宿',
      distValue: '住宿',
      sort: 9,
    },
    {
      id: 10,
      type: 'expenseType',
      distKey: '其他',
      distValue: '其他',
      sort: 10,
    },
    {
      id: 11,
      type: 'paymentType',
      distKey: '支付宝',
      distValue: '支付宝',
      sort: 1,
    },
    {
      id: 12,
      type: 'paymentType',
      distKey: '微信',
      distValue: '微信',
      sort: 2,
    },
    {
      id: 13,
      type: 'paymentType',
      distKey: '京东白条',
      distValue: '京东白条',
      sort: 3,
    },
    {
      id: 14,
      type: 'paymentType',
      distKey: '刷卡',
      distValue: '刷卡',
      sort: 4,
    },
    {
      id: 15,
      type: 'paymentType',
      distKey: '现金',
      distValue: '现金',
      sort: 5,
    },
    {
      id: 16,
      type: 'paymentType',
      distKey: '其他',
      distValue: '其他',
      sort: 6,
    },
  ];
}
