name: Test Docker

on:
  workflow_dispatch:
    inputs:
      target:
        description: 输入打包版本号
        required: true

jobs:
  docker_build:
    environment: docker_hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main-pgsql

      - name: Get version
        id: get_version
        run: |
          VERSION="${{ github.event.inputs.target }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 设置 Docker Buildx (支持多平台构建)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 单次构建多平台镜像并推送（与正式版一致）
      - name: Build and push multi-platform image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag dingdangdog/cashbook:${VERSION}-pgsql \
            --tag dingdangdog/cashbook:latest-pgsql \
            --push .

      - name: Clean up Docker images
        run: docker system prune -af
